/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rpc_H
#define rpc_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "clientRegionServer_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class rpcIf {
 public:
  virtual ~rpcIf() {}
  virtual void sendCommand(std::string& _return, const std::string& command) = 0;
};

class rpcIfFactory {
 public:
  typedef rpcIf Handler;

  virtual ~rpcIfFactory() {}

  virtual rpcIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(rpcIf* /* handler */) = 0;
  };

class rpcIfSingletonFactory : virtual public rpcIfFactory {
 public:
  rpcIfSingletonFactory(const ::std::shared_ptr<rpcIf>& iface) : iface_(iface) {}
  virtual ~rpcIfSingletonFactory() {}

  virtual rpcIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(rpcIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<rpcIf> iface_;
};

class rpcNull : virtual public rpcIf {
 public:
  virtual ~rpcNull() {}
  void sendCommand(std::string& /* _return */, const std::string& /* command */) override {
    return;
  }
};

typedef struct _rpc_sendCommand_args__isset {
  _rpc_sendCommand_args__isset() : command(false) {}
  bool command :1;
} _rpc_sendCommand_args__isset;

class rpc_sendCommand_args {
 public:

  rpc_sendCommand_args(const rpc_sendCommand_args&);
  rpc_sendCommand_args& operator=(const rpc_sendCommand_args&);
  rpc_sendCommand_args() noexcept
                       : command() {
  }

  virtual ~rpc_sendCommand_args() noexcept;
  std::string command;

  _rpc_sendCommand_args__isset __isset;

  void __set_command(const std::string& val);

  bool operator == (const rpc_sendCommand_args & rhs) const
  {
    if (!(command == rhs.command))
      return false;
    return true;
  }
  bool operator != (const rpc_sendCommand_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const rpc_sendCommand_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class rpc_sendCommand_pargs {
 public:


  virtual ~rpc_sendCommand_pargs() noexcept;
  const std::string* command;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _rpc_sendCommand_result__isset {
  _rpc_sendCommand_result__isset() : success(false) {}
  bool success :1;
} _rpc_sendCommand_result__isset;

class rpc_sendCommand_result {
 public:

  rpc_sendCommand_result(const rpc_sendCommand_result&);
  rpc_sendCommand_result& operator=(const rpc_sendCommand_result&);
  rpc_sendCommand_result() noexcept
                         : success() {
  }

  virtual ~rpc_sendCommand_result() noexcept;
  std::string success;

  _rpc_sendCommand_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const rpc_sendCommand_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const rpc_sendCommand_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const rpc_sendCommand_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _rpc_sendCommand_presult__isset {
  _rpc_sendCommand_presult__isset() : success(false) {}
  bool success :1;
} _rpc_sendCommand_presult__isset;

class rpc_sendCommand_presult {
 public:


  virtual ~rpc_sendCommand_presult() noexcept;
  std::string* success;

  _rpc_sendCommand_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class rpcClient : virtual public rpcIf {
 public:
  rpcClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  rpcClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sendCommand(std::string& _return, const std::string& command) override;
  void send_sendCommand(const std::string& command);
  void recv_sendCommand(std::string& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class rpcProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<rpcIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (rpcProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_sendCommand(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  rpcProcessor(::std::shared_ptr<rpcIf> iface) :
    iface_(iface) {
    processMap_["sendCommand"] = &rpcProcessor::process_sendCommand;
  }

  virtual ~rpcProcessor() {}
};

class rpcProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  rpcProcessorFactory(const ::std::shared_ptr< rpcIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< rpcIfFactory > handlerFactory_;
};

class rpcMultiface : virtual public rpcIf {
 public:
  rpcMultiface(std::vector<std::shared_ptr<rpcIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~rpcMultiface() {}
 protected:
  std::vector<std::shared_ptr<rpcIf> > ifaces_;
  rpcMultiface() {}
  void add(::std::shared_ptr<rpcIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void sendCommand(std::string& _return, const std::string& command) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sendCommand(_return, command);
    }
    ifaces_[i]->sendCommand(_return, command);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class rpcConcurrentClient : virtual public rpcIf {
 public:
  rpcConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  rpcConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sendCommand(std::string& _return, const std::string& command) override;
  int32_t send_sendCommand(const std::string& command);
  void recv_sendCommand(std::string& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
